### ISSUE TITLE
알람 서버 docker compose 설계

### ISSUE THREAD

**Issue by MALLLAG** [MoonKimTeam/backend-alarm#2]

**Comment by DonggeonMoon** [comment]
```yaml
version: '3'
services:
  # 알람 서비스 DB
    alarm-db:
        image: mysql:latest
        ports:
           - "3306:3306"
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: "alarms"
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - ./volume/alarm-db:/var/lib/mysql
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./volume/redis/data:/data
      - ./volume/redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    command: redis-server /usr/local/conf/redis.conf
    networks:
      - backend

networks:
  backend:
    driver: bridge
```
